### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by banesullivan** [sdorkenw/MeshParty#32]
This software is pretty cool! Are there any plans to host documentation built with something like Sphinx?

**Comment by ceesem** [comment]
It's definitely planned! The three of us most actively developing meshparty are scientists using it for biological analysis of high resolution neuronal anatomy data. While the goal is to make it a useful tool for other researchers, our first step is to make it useful for ourselves. We are currently balancing tool development with our own research projects. In terms of timing, I expect documentation will become a priority when we submit our first paper that uses it for analysis, which hopefully isn't too far off right now.

**Comment by fcollman** [comment]
@banesullivan  here's our draft docs on readthedocs... PR is open now. 
https://meshparty.readthedocs.io/en/docs/index.html

**Comment by fcollman** [comment]
I think this is now addressed!
