### ISSUE TITLE
a couple installation bugs

### ISSUE THREAD

**Issue by gocker** [sdorkenw/MeshParty#6]
A couple things I've run into installing MeshParty: 

The current version of trimesh (v2.36.4) is missing the io function which is used in trimesh_io.py (trimesh v 2.35.48 works).

rtree isn't in the dependencies. igraph also isn't in the dependencies, and it should be called jgraph (according to the deprecation warning copied below).

Deprecation warning for igraph:

---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-1-73d702af16b7> in <module>
      1 import vtk
      2 from annotationframeworkclient import infoservice
----> 3 from meshparty import skeletonize
      4 from meshparty import trimesh_vtk
      5 from meshparty import trimesh_io

~/anaconda2/envs/em_env/lib/python3.6/site-packages/meshparty-0.2.1-py3.6.egg/meshparty/skeletonize.py in <module>
      3 import time
      4 from meshparty import trimesh_vtk
----> 5 from meshparty import trimesh_io
      6 import pandas as pd
      7 from scipy.spatial import cKDTree as KDTree

~/anaconda2/envs/em_env/lib/python3.6/site-packages/meshparty-0.2.1-py3.6.egg/meshparty/trimesh_io.py in <module>
     17 import vtk
     18 from tqdm import trange
---> 19 import igraph
     20 import rtree
     21 

~/anaconda2/envs/em_env/lib/python3.6/site-packages/igraph/__init__.py in <module>
      6 __license__ = "MIT"
      7 
----> 8 raise DeprecationWarning("To avoid name collision with the igraph project, "
      9                          "this visualization library has been renamed to "
     10                          "'jgraph'. Please upgrade when convenient.")

DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

**Comment by sdorkenw** [comment]
@gocker I guess this issue is fixed?

**Comment by gocker** [comment]
@sdorkenw To check, I just pulled the master branch and tried to install Meshparty in a fresh 3.6 conda environment. I don't get the same bugs, but am now having some issues with pymeshfix now -

"
error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'
    error: command 'gcc' failed with exit status 1
"

**Comment by sdorkenw** [comment]
Could you try again with the latest version. I believe there were some changes in pymeshfix.

**Comment by gocker** [comment]
In a new environment I needed to install gcc. After that I also needed to install clang and the command line tools (xcode-select --install) and cctools (not sure if cctools was necessary). The final thing to get it to work was sudo /usr/sbin/installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
