### ISSUE TITLE
Error using the trimesh_io.download_meshes function

### ISSUE THREAD

**Issue by jboulanger91** [sdorkenw/MeshParty#93]
Thanks for fixing the last error but it seems there is another one now: 

`~/MeshParty/meshparty/trimesh_io.py in _download_meshes_thread_precomputed(args)
    364         download_segids = download_segids[len(download_now):]
    365         if isinstance(cv.mesh, ShardedMultiLevelPrecomputedMeshSource):
--> 366             cv_meshes = cv.mesh.get(download_now, fuse=False)
    367         else:
    368             cv_meshes = cv.mesh.get(

TypeError: get() got an unexpected keyword argument 'fuse'`

Thanks a lot for your help.
Best, 
Jon

**Comment by fcollman** [comment]
ah sorry should have fully tested it, i have now, removed fuse too, and i downloaded some meshes.  I'm sorry we don't have the code infrastructure in place to pass the options that are available so it will default only to downloading lod=0 versions of meshes.  You'll have to wrap your own parallel download option or download the source and inject in a lod=X kwarg if you want to do something other than that for now.

**Comment by fcollman** [comment]
meshparty-1.16.13 should have this fix

**Comment by jboulanger91** [comment]
Thanks. It works :)
